version: '3.7'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
  redis_db:
    container_name: redis_db
    image: redis:latest
    ports:
      - 6379:6379